# Generated by Django 2.2.4 on 2019-09-03 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordering.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0014_sellermerchandise_record_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenderReciept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField()),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('reciept', models.FileField(upload_to=ordering.models.VenderReciept.get_upload_location)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Vender')),
            ],
            options={
                'verbose_name_plural': 'Reciepts',
            },
        ),
    ]
