# Generated by Django 2.2.4 on 2019-09-06 21:31

from django.db import migrations, models
import ordering.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VenderReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True)),
                ('order_date', models.DateTimeField(blank=True, null=True)),
                ('order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('receipt', models.FileField(upload_to=ordering.models.VenderReceipt.get_upload_location)),
            ],
            options={
                'verbose_name_plural': 'receipts',
            },
        ),
    ]
