# Generated by Django 2.2.4 on 2019-09-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0002_auto_20190906_1531'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venderreceipt',
            options={'verbose_name_plural': 'Receipts'},
        ),
    ]
