# Generated by Django 2.2.4 on 2019-08-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_merchandise_seller'),
        ('inventory', '0003_auto_20190827_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerinventory',
            name='inventory',
            field=models.ManyToManyField(to='products.Merchandise'),
        ),
    ]
