# Generated by Django 2.2.4 on 2019-08-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sellerinventory_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellerinventory',
            name='inventory',
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sellerinventory',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
