# Generated by Django 2.2.4 on 2019-09-10 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Seller Stats', max_length=150)),
                ('gross_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('net_income', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('inventory_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('on_floor_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('seller', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Seller Stats',
            },
        ),
    ]
