# Generated by Django 2.2.4 on 2019-08-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WholesaleMerchandise',
            new_name='VenderMerchandise',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True, unique=True),
        ),
    ]
