# Generated by Django 2.2.4 on 2019-08-27 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190826_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='seller',
        ),
    ]
