# Generated by Django 2.2.4 on 2019-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190824_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='QTY',
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='resale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Suggested retail'),
        ),
    ]
