# Generated by Django 2.2.4 on 2019-09-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20190906_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=6, null=True),
        ),
    ]
