# Generated by Django 2.2.4 on 2019-08-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190827_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchandise',
            name='QTY',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='SKU',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='title',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
