# Generated by Django 2.2.4 on 2019-08-29 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_merchandise_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchandise',
            name='on_floor',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
