# Generated by Django 2.2.4 on 2019-08-30 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merchandise_on_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_title', models.CharField(max_length=250)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='merchandise',
            name='on_floor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Selling'),
        ),
        migrations.CreateModel(
            name='SellerMerchandise',
            fields=[
                ('merchandise_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.Merchandise')),
                ('expenses', models.ManyToManyField(to='products.Expense')),
            ],
            options={
                'verbose_name_plural': 'Seller Merchandise',
            },
            bases=('products.merchandise',),
        ),
    ]
