# Generated by Django 2.2.4 on 2019-08-30 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190830_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='vender',
        ),
        migrations.AddField(
            model_name='vendermerchandise',
            name='vender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Vender'),
        ),
    ]
