# Generated by Django 2.2.4 on 2019-08-30 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20190830_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermerchandise',
            name='class_name',
            field=models.CharField(blank=True, default='seller', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='vendermerchandise',
            name='class_name',
            field=models.CharField(blank=True, default='vender', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sellermerchandise',
            name='expenses',
            field=models.ManyToManyField(blank=True, null=True, to='products.Expense'),
        ),
    ]
