# Generated by Django 2.2.4 on 2019-08-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20190830_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermerchandise',
            name='expenses',
            field=models.ManyToManyField(blank=True, to='products.Expense'),
        ),
    ]
