# Generated by Django 2.2.4 on 2019-08-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190830_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
