# Generated by Django 2.2.4 on 2019-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20190830_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellermerchandise',
            name='class_name',
        ),
        migrations.RemoveField(
            model_name='vendermerchandise',
            name='class_name',
        ),
        migrations.AddField(
            model_name='merchandise',
            name='class_name',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
