# Generated by Django 2.2.4 on 2019-09-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20190830_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermerchandise',
            name='record_stats',
            field=models.BooleanField(default=True),
        ),
    ]
